# Remember to restart the service after changing the config file

telegram_bot_token: accesstoken

server_logs:
  - name: Server 1
    path: /complete/path/to/log/file.log

  - name: Server 2
    path: /another/path/to/log/file.log

users:
  - name: username
    enabled: true
    login_msg: true
    logout_msg: true
    search: MinecraftNickName
    pushover_key: key here
    pushover_token: token
    telegram_chat_id: chatidhere
    notify_with: [pushover, pushbullet, nma, telegram]
    pushbullet_token: put token here
    #pushbullet_device: can be empty to send notification to all devices
    nma_key: nmakey here

  - name: username2
    enabled: true
    login_msg: true
    logout_msg: true
    search: MinecraftNickName2
    pushover_key: key here
    pushover_token: token
    telegram_chat_id: key here
    notify_with: [pushover, pushbullet, nma, telegram]
    #pushbullet_token: put token here
    #pushbullet_device: can be empty to send notification to all devices
