# Remember to restart the service after changing the config file

telegram_bot_token: accesstoken

logging:
  level: INFO
  # file: test.log

regex:
  demo_in: 1\s(.+)
  demo_out: 2\s(.+)

logfiles:
  - name: Server 1
    path: /test
    regex: {login: demo_in, logout: demo_out}

users:
  - name: username
    enabled: true
    login_msg: true
    logout_msg: true
    nicknames: [nickname1, 'nickname_2']
    pushover_key: key here
    pushover_token: token
    telegram_chat_id: chatidhere
    notify_with: [pushover, nma, telegram]
    nma_key: nmakey here

  - name: username2
    enabled: true
    login_msg: true
    logout_msg: true
    search: MinecraftNickName2
    pushover_key: key here
    pushover_token: token
    telegram_chat_id: key here
    notify_with: [pushover, telegram]
